# Generated by Django 5.2.5 on 2025-10-04 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='pdf_filename',
            field=models.CharField(default='id', max_length=255),
            preserve_default=False,
        ),
    ]
