# Generated by Django 5.2.5 on 2025-10-04 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0002_bill_pdf_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='pdf_filename',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
