# Generated by Django 5.2.5 on 2025-10-04 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0003_alter_bill_pdf_filename'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bill',
            unique_together={('meter', 'month', 'year')},
        ),
    ]
